export const TILE_SIZE = 32;

export const TILES = {
    EMPTY: 0,
    GRASS: 1,
    WATER: 2,
    MOUNTAIN: 3,
    HOUSE: 4,
    TREE: 5,
    SHOP: 6,
    BOT: 7,
    CREEP: 8,
    BOSS: 9,
    TELEPORT: 10,
    // New Tiles for Detail
    GRASS_VARIANT: 11,
    FLOWER: 12,
    BUSH: 13,
    PATH: 14,
    WATER_LILY: 15,
    CRYSTAL: 16,
    MUSHROOM: 17,
    SIGN: 18,
    FENCE: 19,
    NPC: 20,
    STORAGE: 21,
    SUMMON_TREE: 22,
    ANVIL: 23,
    // Enemy types
    SPIDER: 30,
    GOBLIN: 31,
    SKELETON: 32,
    DARK_WIZARD: 33,
    ELF: 34,
    GOLEM: 35,
    DRAGON: 36,
    DEMON: 37,
    ORC: 38,
    WOLF: 39,
    BAT: 40,
    SERPENT: 41,
    UNDEAD_KNIGHT: 42,
    SHADOW: 43,
    ELEMENTAL: 44,
    // Farm & Defense
    FARM_SOIL: 50,
    DEFENSE_SLOT: 55,
    DEFENSE_PLANT: 56,
};

// Map tile types to image sources
// Fallback logic will use these names to find files in /assets/rpg/
export const TILE_IMAGES = {
    [TILES.GRASS]: 'grass.png',
    [TILES.WATER]: 'water.png',
    [TILES.MOUNTAIN]: 'mountain.png',
    [TILES.HOUSE]: 'house.png',
    [TILES.TREE]: 'tree.png',
    [TILES.SHOP]: 'shop.png',
    [TILES.BOT]: 'bot.png',
    [TILES.CREEP]: 'creep.png',
    [TILES.BOSS]: 'boss.png',
    [TILES.TELEPORT]: 'teleport.png',
    [TILES.GRASS_VARIANT]: 'grass_v.png',
    [TILES.FLOWER]: 'flower.png',
    [TILES.BUSH]: 'bush.png',
    [TILES.PATH]: 'path.png',
    [TILES.WATER_LILY]: 'lily.png',
    [TILES.CRYSTAL]: 'crystal.png',
    [TILES.MUSHROOM]: 'mushroom.png',
    [TILES.SIGN]: 'sign.png',
    [TILES.FENCE]: 'fence.png',
    [TILES.NPC]: 'npc.png',
    [TILES.STORAGE]: 'storage.png',
    [TILES.SUMMON_TREE]: 'summon_tree.png',
    [TILES.ANVIL]: 'anvil.png',
    // Enemy types
    [TILES.SPIDER]: 'spider.png',
    [TILES.GOBLIN]: 'goblin.png',
    [TILES.SKELETON]: 'skeleton.png',
    [TILES.DARK_WIZARD]: 'dark_wizard.png',
    [TILES.ELF]: 'elf.png',
    [TILES.GOLEM]: 'golem.png',
    [TILES.DRAGON]: 'dragon.png',
    [TILES.DEMON]: 'demon.png',
    [TILES.ORC]: 'orc.png',
    [TILES.WOLF]: 'wolf.png',
    [TILES.BAT]: 'bat.png',
    [TILES.SERPENT]: 'serpent.png',
    [TILES.UNDEAD_KNIGHT]: 'undead_knight.png',
    [TILES.SHADOW]: 'shadow.png',
    [TILES.ELEMENTAL]: 'elemental.png',
};

// Fallback colors matching the reference vividness
export const TILE_COLORS = {
    [TILES.EMPTY]: '#000000',
    [TILES.GRASS]: '#4caf50',
    [TILES.GRASS_VARIANT]: '#43a047',
    [TILES.WATER]: '#2196f3',
    [TILES.MOUNTAIN]: '#795548',
    [TILES.HOUSE]: '#ff9800',
    [TILES.TREE]: '#1b5e20',
    [TILES.SHOP]: '#e91e63',
    [TILES.BOT]: '#9c27b0',
    [TILES.CREEP]: '#f44336',
    [TILES.BOSS]: '#b71c1c',
    [TILES.TELEPORT]: '#00bcd4',
    [TILES.FLOWER]: '#e91e63',
    [TILES.BUSH]: '#33691e',
    [TILES.PATH]: '#d7ccc8',
    [TILES.WATER_LILY]: '#81c784',
    [TILES.CRYSTAL]: '#e040fb',
    [TILES.MUSHROOM]: '#ff5722',
    [TILES.SIGN]: '#a1887f',
    [TILES.FENCE]: '#8d6e63',
    [TILES.NPC]: '#ffab40',
    [TILES.STORAGE]: '#8d6e63',
    [TILES.ANVIL]: '#757575',
    [TILES.SUMMON_TREE]: '#aa00ff',
    // Enemy types
    [TILES.SPIDER]: '#4a2810',
    [TILES.GOBLIN]: '#558b2f',
    [TILES.SKELETON]: '#e0e0e0',
    [TILES.DARK_WIZARD]: '#6a1b9a',
    [TILES.ELF]: '#66bb6a',
    [TILES.GOLEM]: '#5d4037',
    [TILES.DRAGON]: '#b71c1c',
    [TILES.DEMON]: '#880e4f',
    [TILES.ORC]: '#33691e',
    [TILES.WOLF]: '#616161',
    [TILES.BAT]: '#311b92',
    [TILES.SERPENT]: '#1b5e20',
    [TILES.UNDEAD_KNIGHT]: '#37474f',
    [TILES.SHADOW]: '#212121',
    [TILES.ELEMENTAL]: '#00838f',
    // Farm & Defense
    [TILES.FARM_SOIL]: '#8d6534',
    [TILES.DEFENSE_SLOT]: '#5d8a3c',
    [TILES.DEFENSE_PLANT]: '#4caf50',
};

export const TILE_NAMES = {
    [TILES.EMPTY]: 'Empty',
    [TILES.GRASS]: 'Grass',
    [TILES.WATER]: 'Water',
    [TILES.MOUNTAIN]: 'Mountain',
    [TILES.HOUSE]: 'House',
    [TILES.TREE]: 'Tree',
    [TILES.SHOP]: 'Shop',
    [TILES.BOT]: 'Bot',
    [TILES.CREEP]: 'Creep',
    [TILES.BOSS]: 'Boss',
    [TILES.TELEPORT]: 'Teleport',
    [TILES.GRASS_VARIANT]: 'Grass (Var)',
    [TILES.FLOWER]: 'Flower',
    [TILES.BUSH]: 'Bush',
    [TILES.PATH]: 'Path',
    [TILES.WATER_LILY]: 'Lilypad',
    [TILES.CRYSTAL]: 'Crystal',
    [TILES.MUSHROOM]: 'Mushroom',
    [TILES.SIGN]: 'Sign',
    [TILES.FENCE]: 'Fence',
    [TILES.NPC]: 'NPC',
    [TILES.STORAGE]: 'Storage',
    [TILES.SUMMON_TREE]: 'Summon Tree',
    [TILES.ANVIL]: 'Anvil',
    // Enemy types
    [TILES.SPIDER]: 'Spider',
    [TILES.GOBLIN]: 'Goblin',
    [TILES.SKELETON]: 'Skeleton',
    [TILES.DARK_WIZARD]: 'Dark Wizard',
    [TILES.ELF]: 'Elf',
    [TILES.GOLEM]: 'Golem',
    [TILES.DRAGON]: 'Dragon',
    [TILES.DEMON]: 'Demon',
    [TILES.ORC]: 'Orc',
    [TILES.WOLF]: 'Wolf',
    [TILES.BAT]: 'Bat',
    [TILES.SERPENT]: 'Serpent',
    [TILES.UNDEAD_KNIGHT]: 'Undead Knight',
    [TILES.SHADOW]: 'Shadow',
    [TILES.ELEMENTAL]: 'Elemental',
    // Farm & Defense
    [TILES.FARM_SOIL]: 'Farm Soil',
    [TILES.DEFENSE_SLOT]: 'Defense Slot',
    [TILES.DEFENSE_PLANT]: 'Defense Plant',
};

// Collision Map
export const WALKABLE = {
    [TILES.EMPTY]: false,
    [TILES.GRASS]: true,
    [TILES.GRASS_VARIANT]: true,
    [TILES.WATER]: false,
    [TILES.MOUNTAIN]: false,
    [TILES.HOUSE]: false,
    [TILES.TREE]: false,
    [TILES.SHOP]: false,
    [TILES.BOT]: true, // Interaction triggers instead of walk
    [TILES.CREEP]: true,
    [TILES.BOSS]: true,
    [TILES.TELEPORT]: true,
    [TILES.FLOWER]: true,
    [TILES.BUSH]: true,
    [TILES.PATH]: true,
    [TILES.WATER_LILY]: true, // Maybe walk if on water edge? False for now.
    [TILES.CRYSTAL]: false,
    [TILES.MUSHROOM]: true,
    [TILES.SIGN]: false,
    [TILES.FENCE]: false,
    [TILES.NPC]: false,
    [TILES.STORAGE]: false,
    [TILES.SUMMON_TREE]: false,
    [TILES.ANVIL]: false,
    // Enemy types (walkable so entities can be placed)
    [TILES.SPIDER]: true, [TILES.GOBLIN]: true, [TILES.SKELETON]: true,
    [TILES.DARK_WIZARD]: true, [TILES.ELF]: true, [TILES.GOLEM]: true,
    [TILES.DRAGON]: true, [TILES.DEMON]: true, [TILES.ORC]: true,
    [TILES.WOLF]: true, [TILES.BAT]: true, [TILES.SERPENT]: true,
    [TILES.UNDEAD_KNIGHT]: true, [TILES.SHADOW]: true, [TILES.ELEMENTAL]: true,
    // Farm & Defense (walkable for click interaction)
    [TILES.FARM_SOIL]: true,
    [TILES.DEFENSE_SLOT]: true,
    [TILES.DEFENSE_PLANT]: false,
};

// Render Layer: 0 = Ground, 1 = Object (Above Ground)
// For simple rendering, if it's an "Object", we might draw it on top of ground.
// In our engine, we will likely have specific layers in the map data, but this helps default placement.
export const IS_OBJECT = {
    [TILES.TREE]: true,
    [TILES.HOUSE]: true,
    [TILES.SHOP]: true,
    [TILES.BOT]: true,
    [TILES.CREEP]: true,
    [TILES.BOSS]: true,
    [TILES.CRYSTAL]: true,
    [TILES.SIGN]: true,
    [TILES.FENCE]: true,
    [TILES.BUSH]: true,
    [TILES.MUSHROOM]: true,
    [TILES.FLOWER]: true,
    [TILES.WATER_LILY]: true,
    [TILES.NPC]: true,
    [TILES.STORAGE]: true,
    [TILES.SUMMON_TREE]: true,
    [TILES.ANVIL]: true,
    // Enemy types
    [TILES.SPIDER]: true, [TILES.GOBLIN]: true, [TILES.SKELETON]: true,
    [TILES.DARK_WIZARD]: true, [TILES.ELF]: true, [TILES.GOLEM]: true,
    [TILES.DRAGON]: true, [TILES.DEMON]: true, [TILES.ORC]: true,
    [TILES.WOLF]: true, [TILES.BAT]: true, [TILES.SERPENT]: true,
    [TILES.UNDEAD_KNIGHT]: true, [TILES.SHADOW]: true, [TILES.ELEMENTAL]: true,
    // Farm & Defense
    [TILES.FARM_SOIL]: true,
    [TILES.DEFENSE_SLOT]: true,
    [TILES.DEFENSE_PLANT]: true,
};
