<?php

namespace Kennofizet\RewardPlay;

use Illuminate\Support\ServiceProvider;

class RewardPlayServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->mergeConfigFrom(
            __DIR__ . '/Config/rewardplay.php',
            'rewardplay'
        );
    }

    public function boot()
    {
        $this->publishes([
            __DIR__ . '/Migrations' => database_path('migrations'),
        ], 'rewardplay-migrations');

        $this->publishes([
            __DIR__ . '/Config/rewardplay.php' => config_path('rewardplay.php'),
        ], 'rewardplay-config');

        // Publish default images folder
        $imagesFolder = config('rewardplay.images_folder', 'rewardplay-images');
        $this->publishes([
            __DIR__ . '/Assets/images' => public_path($imagesFolder),
        ], 'rewardplay-images');

        // Publish constants folder (generated by rewardplay:export-constants)
        $constantsFolder = config('rewardplay.constants_folder', 'rewardplay-constants');
        $this->publishes([
            __DIR__ . '/Assets/constant' => public_path($constantsFolder),
        ], 'rewardplay-constants');

        // Register custom commands
        if ($this->app->runningInConsole()) {
            $this->commands([
                \Kennofizet\RewardPlay\Commands\PublishImagesCommand::class,
                \Kennofizet\RewardPlay\Commands\PublishConstantsCommand::class,
                \Kennofizet\RewardPlay\Commands\ExportConstantsCommand::class,
                \Kennofizet\RewardPlay\Commands\ManageRewardPlayCommand::class,
                \Kennofizet\RewardPlay\Commands\SnapshotRankingCommand::class,
            ]);
        }

        $this->loadRoutesFrom(__DIR__ . '/Routes/api.php');
    }
}
