<?php

namespace Kennofizet\RewardPlay\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Kennofizet\RewardPlay\Models\SettingItem\SettingItemConstant;
use Kennofizet\RewardPlay\Models\SettingShopItem\SettingShopItemConstant;
use Kennofizet\RewardPlay\Helpers\Constant as HelperConstant;

/**
 * Export PHP constants to a JS file for frontend use.
 * Generates Assets/constant/rewardplay-constants.js and assigns window.REWARDPLAY_CONSTANTS.
 */
class ExportConstantsCommand extends Command
{
    protected $signature = 'rewardplay:export-constants
                            {--output= : Custom output path (default: package Assets/constant)}';

    protected $description = 'Export RewardPlay PHP constants to a JS file for frontend';

    /** Constant names to skip when exporting (backend-only, not needed by frontend). */
    private const SKIP_CONSTANT_NAMES = [
        'API_SETTING_ITEM_LIST_PAGE',
        'API_LIST_PAGE',
        'TABLE_NAME',
        'IS_DELETED_STATUS_COLUMN',
        'ZONE_ID_COLUMN',
        'SERVER_ID_COLUMN',
        'REPONSE_MODE_SELECTER_API',
        'STATUS_COLUMN',
        'DEFAULT_EXP_NEEDED',
        'BOX_RANDOM_RATE_LIST',
        'BOX_RANDOM_ITEM_COUNT',
    ];

    /** Helper: only these constants are exported (all others skipped). */
    private const HELPER_KEEP_NAMES = [
        'TYPE_COIN',
        'TYPE_EXP',
        'TYPE_GEAR',
        'TYPE_TICKET',
        'TYPE_RUBY',
        'REPONSE_MODE_SELECTER_API',
    ];

    public function handle(): int
    {
        $constants = $this->collectConstants();

        $json = json_encode($constants, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        if ($json === false) {
            $this->error('Failed to encode constants to JSON');
            return self::FAILURE;
        }

        $js = $this->buildJsFile($json);

        $outputPath = $this->option('output');
        if ($outputPath === null || $outputPath === '') {
            $outputPath = __DIR__ . '/../Assets/constant/rewardplay-constants.js';
        }

        $dir = dirname($outputPath);
        if (!File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        File::put($outputPath, $js);
        $this->info("Constants exported to: {$outputPath}");

        return self::SUCCESS;
    }

    /**
     * Collect all public constants from backend Constant classes used by frontend.
     *
     * @return array<string, array<string, mixed>>
     */
    private function collectConstants(): array
    {
        $classes = [
            'SettingItem' => SettingItemConstant::class,
            'SettingShopItem' => SettingShopItemConstant::class,
            'Helper' => HelperConstant::class,
        ];

        $result = [];
        foreach ($classes as $key => $class) {
            $ref = new \ReflectionClass($class);
            $constants = $ref->getConstants();
            if ($key === 'Helper') {
                $result[$key] = array_intersect_key($constants, array_flip(self::HELPER_KEEP_NAMES));
            } else {
                $result[$key] = array_diff_key($constants, array_flip(self::SKIP_CONSTANT_NAMES));
            }
        }

        return $result;
    }

    private function buildJsFile(string $json): string
    {
        return <<<JS
/**
 * RewardPlay constants - generated by rewardplay:export-constants
 * Do not edit by hand. Run: php artisan rewardplay:export-constants
 * Then publish: php artisan rewardplay:publish-constants
 */
(function () {
  'use strict';
  window.REWARDPLAY_CONSTANTS = {$json};
})();

JS;
    }
}
